#
# Purpose:
#   Installs the OpenShift cli client binaries and other complimentary tools used to operate an
#   OpenShift/Kubernetes cluster. Binaries are installed in /usr/local/bin.
#
#     - openshift-install binary
#     - oc binary
#     - kubectl binary
#     - butane binary
#     - helm binary
#
# Package source:
#   https://mirror.openshift.com/pub/
#
# Variables:
#   - repo_base_url: (string, required). Default: "none"
#   - ocp_arch: (string, required). Default: "none"
#   - ocp_version: (string, required). Default: "none"
#   - ocp_package: (list, required). Default: "none"
#   - butane_version: (string, required). Default: "none"
#   - butane_package: (string, required). Default: "none"
#   - helm_version: (string, required). Default: "none"
#   - helm_package: (string, required). Default: "none"
#
# Tags:
#   - [install_ocp_client]
#   - [install_butane_client]
#   - [install_helm_client]
# ---
---
- name: Install Linux programs needed to install OpenShift
  hosts: localhost
  vars:
    repo_base_url: 'https://mirror.openshift.com/pub/openshift-v4'
    ocp_arch: amd64
    ocp_version: 4.20.8
    ocp_package:
      - 'openshift-client-linux-{{ ocp_version }}.tar.gz'
      - 'openshift-install-linux-{{ ocp_version }}.tar.gz'
    butane_version: v0.25.1-1
    butane_package: 'butane-{{ ocp_arch }}'
    helm_version: 3.17.1
    helm_package: 'helm-linux-{{ ocp_arch }}'

  tasks:
    - name: Get OpenShift clients currently installed version
      shell: |
        /usr/local/bin/oc version --client -o json | jq -r .releaseClientVersion
      register: oc_client_version
      changed_when: false
      tags:
        - install_ocp_client

    - name: Set fact for current OpenShift client installation
      set_fact:
        oc_version_installed: '{{ oc_client_version.stdout }}'
      tags:
        - install_ocp_client

    - name: Remove previous versions of OpenShift clients if target version is different
      ansible.builtin.file:
        path: '/usr/local/bin/{{ item }}'
        state: absent
      loop:
        - openshift-install
        - oc
        - kubectl
      when:
        - ansible_facts['system'] == 'Linux'
        - ansible_facts['architecture'] == 'x86_64'
        - oc_version_installed != ocp_version
      tags:
        - install_ocp_client

    - name: 'Install OpenShift clients version: {{ ocp_version }}'
      ansible.builtin.unarchive:
        src: '{{ repo_base_url }}/{{ ocp_arch }}/clients/ocp/{{ ocp_version }}/{{ item }}'
        dest: /usr/local/bin
        remote_src: yes
        exclude:
          - README.md
      loop: '{{ ocp_package }}'
      when:
        - ansible_facts['system'] == 'Linux'
        - ansible_facts['architecture'] == 'x86_64'
        - oc_version_installed != ocp_version
      tags:
        - install_ocp_client

    - name: 'Install Butane client version: {{ butane_version }}'
      ansible.builtin.get_url:
        url: '{{ repo_base_url }}/{{ ocp_arch }}/clients/butane/{{ butane_version }}/{{ butane_package }}'
        dest: /usr/local/bin/butane
        mode: 755
      when:
        - ansible_facts['system'] == 'Linux'
        - ansible_facts['architecture'] == 'x86_64'
      tags:
        - install_butane_client

    - name: 'Install Helm client version: {{ helm_version }}'
      ansible.builtin.get_url:
        url: '{{ repo_base_url }}/{{ ocp_arch }}/clients/helm/{{ helm_version }}/{{ helm_package }}'
        dest: /usr/local/bin/helm
        mode: 0755 
      when:
        - ansible_facts['system'] == 'Linux'
        - ansible_facts['architecture'] == 'x86_64'
      tags:
        - install_helm_client

    - name: We are done here. Goodbye horses.....
      ansible.builtin.debug:
        msg:
          - 'The Openshift client and friends are  now installed under the /usr/local/bin directory.'
          - 'Make sure /usr/local/bin exists in your shells $PATH'
          - 'For the latest releases of these binaries: https://mirror.openshift.com/pub/'
          - 'You break it, you buy it, my friend.'
      when:
        - ansible_facts['system'] == 'Linux'
        - ansible_facts['architecture'] == 'x86_64'
      tags:
        - install_ocp_client
        - install_butane_client
        - install_helm_client
        - bye
